apiVersion: v1
kind: Namespace
metadata:
  name: semantic-kernel-consumer
  labels:
    app: semantic-kernel-consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantic-kernel-consumer
  namespace: semantic-kernel-consumer
  labels:
    app: semantic-kernel-consumer
    version: "0.1"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: semantic-kernel-consumer
  template:
    metadata:
      labels:
        app: semantic-kernel-consumer
        version: "0.1"
    spec:
      serviceAccountName: semantic-kernel-consumer-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: semantic-kernel-consumer
        image: genaigateway.azurecr.io/semantic-kernel-consumer:0.3
        imagePullPolicy: IfNotPresent
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: PYTHONPYCACHEPREFIX
          value: "/tmp/__pycache__"
        - name: SHUTDOWN_TIMEOUT
          value: "30"
        # Azure Service Bus Configuration (mapped to expected names)
        - name: SERVICE_BUS_CONNECTION_STR
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: service-bus-connection-string
        - name: SERVICE_BUS_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: service-bus-queue-name
        # Azure Storage Configuration
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: storage-connection-string
        # Azure OpenAI Configuration (mapped to expected names)
        - name: AI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: openai-endpoint
        - name: AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: openai-api-key
        - name: AI_MODEL_NAME
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: ai-model-name
        - name: API_VERSION
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: api-version
        # Managed Identity (if using Azure Workload Identity)
        - name: AZURE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: azure-config
              key: client-id
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: app-tmp
          mountPath: /app/tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: app-logs
        emptyDir: {}
      - name: app-tmp
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: semantic-kernel-consumer-sa
  namespace: semantic-kernel-consumer
  labels:
    app: semantic-kernel-consumer
  annotations:
    # Uncomment and configure if using Azure Workload Identity
    # azure.workload.identity/client-id: "your-managed-identity-client-id"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-config
  namespace: semantic-kernel-consumer
  labels:
    app: semantic-kernel-consumer
data:
  # Azure OpenAI Configuration
  openai-endpoint: "https://genai-gateway.cognitiveservices.azure.com/openai/deployments/gpt-4.1"
  ai-model-name: "gpt-4.1"  # Replace with your actual deployment name
  api-version: "2024-12-01-preview"  # Replace with your preferred API version
  
  # Azure Service Bus Configuration
  service-bus-queue-name: "essay-evaluation-queue"  # Replace with your actual queue name
  
  # Managed Identity Configuration
  client-id: "3bb6eaaf-4f1c-4ae0-a6fc-7d7bf0c8a474"
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
  namespace: semantic-kernel-consumer
  labels:
    app: semantic-kernel-consumer
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded secrets
  service-bus-connection-string: "RW5kcG9pbnQ9c2I6Ly9nZW5haS1nYXRld2F5LnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9cmVhZDtTaGFyZWRBY2Nlc3NLZXk9NGZINUJxd1lGWmQ5N0J4R2FxaWk0NHRpd2xpRkxxTE1qK0FTYktRcnF5QT0="
  storage-connection-string: "RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWdlbmFpZ2F0ZXdheTtBY2NvdW50S2V5PUpwT1YxTG9MUHhWcXhyR3hvRSswWHRKejBkVlBhVTBzNVRISVpzZ0pnUkxYNlQyd2pFSmJ1YWVUMlVZWTFXNHhQQWJNTGgxSlNFWk8rQVN0cXE4dUFRPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA=="
  openai-api-key: "QzNtNDR2bTk3SjhsTlVVVmphVzFCMXFQQmVqNTc3bU5wRDJhRVgyRzlQbEdmM3lOQWdZWkpRUUo5OUJIQUNZZUJqRlhKM3czQUFBQUFDT0dTVTRR"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: semantic-kernel-consumer-netpol
  namespace: semantic-kernel-consumer
spec:
  podSelector:
    matchLabels:
      app: semantic-kernel-consumer
  policyTypes:
  - Egress
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS for Azure services
    - protocol: TCP
      port: 5671 # Service Bus AMQP over SSL
    - protocol: TCP
      port: 5672 # Service Bus AMQP
    - protocol: TCP
      port: 53   # DNS
    - protocol: UDP
      port: 53   # DNS
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: semantic-kernel-consumer-pdb
  namespace: semantic-kernel-consumer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: semantic-kernel-consumer
