# Azure Workload Identity Configuration
# This file contains the necessary resources for Azure Workload Identity
# Uncomment and configure if you want to use Azure Workload Identity instead of connection strings

apiVersion: v1
kind: ServiceAccount
metadata:
  name: semantic-kernel-consumer-workload-identity
  namespace: semantic-kernel-consumer
  labels:
    app: semantic-kernel-consumer
  annotations:
    azure.workload.identity/client-id: "3bb6eaaf-4f1c-4ae0-a6fc-7d7bf0c8a474"
    azure.workload.identity/tenant-id: "61a8746e-424d-4105-a054-b38573d6e54a"
automountServiceAccountToken: true
---
# Federated Identity Credential needs to be created via Azure CLI or Portal
# az identity federated-credential create \
#   --name "semantic-kernel-consumer-federated-credential" \
#   --identity-name "semantic-kernel-consumer-identity" \
#   --resource-group "your-resource-group" \
#   --issuer "https://your-aks-cluster-oidc-issuer-url" \
#   --subject "system:serviceaccount:semantic-kernel-consumer:semantic-kernel-consumer-workload-identity"
